// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpihdegtiayflpxncdaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwaWhkZWd0aWF5ZmxweG5jZGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODc1NDksImV4cCI6MjA3MjA2MzU0OX0.GDEv_EGXybtzZ2uaQ0BJXY83ZqgT_nxrPCzq8vctO64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});